### ISSUE TITLE
Live Demo Doesn't Work

### ISSUE THREAD

**Issue by OldAidan** [kandanapp/kandan#418]
The Demo app on this projects website does not currently work.
![screen shot 2014-12-14 at 10 58 32 pm](https://cloud.githubusercontent.com/assets/8172869/5431062/d049ae8e-83e4-11e4-8691-efd5eb076c5f.png)

**Comment by carlsmith** [comment]
It's not working again. I'm seeing the same error message as above.

**Comment by scouttyg** [comment]
Alright should be good to go, sorry for the inconvenience!

**Comment by carlsmith** [comment]
Yep. All working now. Cheers.

Nice work by the way. We use Slack, and the pricing doesn't work for us as we have thousands of people on there. This looks really promising.

**Comment by scouttyg** [comment]
Thanks for the feedback! It's a work in progress, let us know how it works for your organization.

**Comment by carlsmith** [comment]
Will do. Thanks again.

**Comment by Huljo** [comment]
Again
