### ISSUE TITLE
Kandan People tab only shows the person logged in.

### ISSUE THREAD

**Issue by AidanHanda** [kandanapp/kandan#428]
When I am in the peoples tab Kandan only shows the person who is logged in. To see new messages I must refresh the page which makes it unusable.
![screenshot_2](https://cloud.githubusercontent.com/assets/8172869/5989677/d92853e4-a954-11e4-90fd-22b10c6a1a70.png)

**Comment by scouttyg** [comment]
Sounds like faye isn't configured properly. If you open up your dev console on the browser, do you see messages warning the connection to faye is down?

**Comment by AidanHanda** [comment]
"[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (faye, line 0)"

Shows up

**Comment by scouttyg** [comment]
Sounds like Faye isn't running correctly, Faye is the pub/sub messaging system we use in Kandan to get messages to show up in realtime. You might need to tell us more about your configuration to help solve this. What are you running kandan on? With what configuration?

**Comment by scouttyg** [comment]
Haven't heard back, so unfortunately I'm going to close this. Let me know if there are any updates!
