### ISSUE TITLE
settings: add option select new port instead of ruby default 3000

### ISSUE THREAD

**Issue by hozmaster** [kandanapp/kandan#433]
I would like change port number to another I've another service runnig in that port.

I'm running in my kandan instance in my own private server.

**Comment by scouttyg** [comment]
You can! When running locally, you can always run ```rails server -p 3001``` for example, to run on port 3001 rather than port 3000. The Procfile also supports supplying a ```$PORT``` variable to do this as well.

**Comment by hozmaster** [comment]
Yes, i'm totally aware that i could run server that way. This is not very flexible way run kandan in my system.

**Comment by scouttyg** [comment]
Could you let us know some things about your system? It's hard to give specific advice as to the best way to help if we don't know the background of how your system was set up.

**Comment by scouttyg** [comment]
I'm going to close this issue, but let me know if you have any updates!
