### ISSUE TITLE
Invalid email addresses 

### ISSUE THREAD

**Issue by radioactivekitty** [kandanapp/kandan#434]
Hello,  I would like to point out that the following emails do not have a mailbox:

* admin@kandan.io
* admin@getkandan.com
* team@getkandan.com

> Technical details of permanent failure:
> Google tried to deliver your message, but it was rejected by the server for the recipient domain 
> getkandan.com by eforward2.registrar-servers.com. [162.213.254.219].
> The error that the other server returned was:
> 550 no mailbox by that name is currently available

(The above remains true for all emails, except for the kandan.io, in which case the domain is different).

Best regards,
Radioactivekitty

**Comment by scouttyg** [comment]
I thought I setup a catchall email that would go, but it looks like it failed me. I just added the new domains in this week, and have been trying to cleanup all instances of things. I'll fix this now.

**Comment by scouttyg** [comment]
Ah, missed a setting. Should be fixed for these, along with contact@getkandan.com and info@getkandan.com, along with the IO domain as well.

**Comment by radioactivekitty** [comment]
Awesome, I'll send a test email :D

**Comment by radioactivekitty** [comment]
Looks like it works, issue closed.
