### ISSUE TITLE
Password protected rooms

### ISSUE THREAD

**Issue by mmeinert** [kandanapp/kandan#441]
It's more a feature request than an issue.

What do you think about password protected rooms ?
Greetings

**Comment by scouttyg** [comment]
I think it's a good idea, and wouldn't be that hard, but I think it might be better to allow an admin to create channels, and allow users in certain channels accordingly, at least in the short term.

In the long term, I think password protected rooms would be quite useful, so we'll add it to the list!

**Comment by mmeinert** [comment]
great !
