### ISSUE TITLE
Issue while deploying to heroku

### ISSUE THREAD

**Issue by Beeneh** [kandanapp/kandan#452]
Hi there,

I'm trying to deploy kandan to heroku. However, i'm getting the following errors while following the small guide in the deploy.md.

`c:\kandan>git clone https://github.com/kandanapp/kandan.git
Cloning into 'kandan'...
remote: Counting objects: 7350, done.
Receiving objects: 100% (7350/7350), 8.74 MiB | 2.82emote: Total 7350 (delta 0),
 reused 0 (delta 0), pack-reused 7350 MiB/s, done.

Resolving deltas: 100% (3345/3345), done.
Checking connectivity... done.

c:\kandan>cd kandan

c:\kandan\kandan>hero create --stack cedar
'hero' is not recognized as an internal or external command,
operable program or batch file.

c:\kandan\kandan>heroku create --stack cedar
Creating app... done, <name>, stack is cedar-14
https://<name>.herokuapp.com/ | https://git.heroku.com/<name>.git

c:\kandan\kandan>git push heroku master
Counting objects: 7251, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3787/3787), done.
Writing objects: 100% (7251/7251), 6.40 MiB | 150.00 KiB/s, done.
Total 7251 (delta 3289), reused 7251 (delta 3289)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.4
remote: -----> Installing dependencies using bundler 1.11.2
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        Fetching gem metadata from https://rubygems.org/.............
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Using rake 10.4.2
remote:        Installing multi_json 1.10.1
remote:        Installing i18n 0.6.11
remote:        Installing builder 3.0.4
remote:        Installing erubis 2.7.0
remote:        Installing journey 1.0.4
remote:        Installing rack 1.4.5
remote:        Installing hike 1.2.3
remote:        Installing mime-types 1.25.1
remote:        Installing tilt 1.4.1
remote:        Installing polyglot 0.3.5
remote:        Installing arel 3.0.3
remote:        Using json 1.8.1
remote:        Installing tzinfo 0.3.42
remote:        Installing addressable 2.3.6
remote:        Installing mini_portile 0.5.3
remote:        Installing uuidtools 2.1.4
remote:        Installing bcrypt 3.1.7 with native extensions
remote:        Installing sass 3.2.13
remote:        Installing thor 0.19.1
remote:        Installing cancancan 1.9.2
remote:        Installing coffee-script-source 1.7.0
remote:        Installing execjs 2.0.2
remote:        Installing cookiejar 0.3.2
remote:        Installing daemons 1.1.9
remote:        Installing orm_adapter 0.5.0
remote:        Installing thread_safe 0.3.3
remote:        Installing eco-source 1.1.0.rc.1
remote:        Installing eventmachine 1.0.3 with native extensions
remote:        Installing http_parser.rb 0.6.0 with native extensions
remote:        Installing websocket-driver 0.3.2 with native extensions
remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:        /tmp/build_f93600f1a2d3c92b36aa27f3bcb00821/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160818-231-18l0wkd.rb extconf.rb
remote:        checking for rb_trap_immediate in ruby.h,rubysig.h... no
remote:        checking for rb_thread_blocking_region()... no
remote:        checking for inotify_init() in sys/inotify.h... yes
remote:        checking for writev() in sys/uio.h... yes
remote:        checking for rb_wait_for_single_fd()... yes
remote:        checking for rb_enable_interrupt()... no
remote:        checking for rb_time_new()... yes
remote:        checking for sys/event.h... no
remote:        checking for epoll_create() in sys/epoll.h... yes
remote:        creating Makefile
remote:        make "DESTDIR=" clean
remote:        make "DESTDIR="
remote:        compiling cmain.cpp
remote:        compiling pipe.cpp
remote:        compiling binder.cpp
remote:        compiling ssl.cpp
remote:        compiling kb.cpp
remote:        compiling rubymain.cpp
remote:        compiling page.cpp
remote:        compiling em.cpp
remote:        em.cpp: In member function 'void EventMachine_t::_RunEpollOnce()':
remote:        em.cpp:574:37: error: 'rb_thread_select' was not declared in this scope
remote:        EmSelect (0, NULL, NULL, NULL, &tv);
remote:        ^
remote:        em.cpp: In member function 'int SelectData_t::_Select()':
remote:        em.cpp:827:67: error: 'rb_thread_select' was not declared in this scope
remote:        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
remote:        ^
remote:        em.cpp: In member function 'void EventMachine_t::_RunSelectOnce()':
remote:        em.cpp:946:40: error: 'rb_thread_select' was not declared in this
 scope
remote:        EmSelect (0, NULL, NULL, NULL, &tv);
remote:        ^
remote:        make: **\* [em.o] Error 1
remote:        make failed, exit code 2
remote:        Gem files will remain installed in /tmp/build_f93600f1a2d3c92b36aa27f3bcb00821/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
remote:        Results logged to /tmp/build_f93600f1a2d3c92b36aa27f3bcb00821/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/eventmachine-1.0.3/gem_make.out
remote:        Installing kandan-count 1.1.1
remote:        Installing gemoji 1.5.0
remote:        Installing pg 0.17.1 with native extensions
remote:        Using bundler 1.11.2
remote:        Installing remotipart 1.2.1
remote:        Installing activesupport 3.2.21
remote:        Installing rack-cache 1.2
remote:        Installing rack-test 0.6.2
remote:        Installing rack-ssl 1.3.4
remote:        Installing warden 1.2.3
remote:        Installing sprockets 2.2.3
remote:        Installing treetop 1.4.15
remote:        Installing rdoc 3.12.2
remote:        Installing bootstrap-sass 3.1.1.0
remote:        Installing nokogiri 1.6.1 with native extensions
remote:        Installing bourbon 3.1.8
remote:        Installing coffee-script 2.2.0
remote:        Installing uglifier 2.5.0
remote:        An error occurred while installing eventmachine (1.0.3), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
remote:        Bundler Output: Fetching gem metadata from https://rubygems.org/.............
remote:        Fetching version metadata from https://rubygems.org/...
remote:        Fetching dependency metadata from https://rubygems.org/..
remote:        Using rake 10.4.2
remote:        Installing multi_json 1.10.1
remote:        Installing i18n 0.6.11
remote:        Installing builder 3.0.4
remote:        Installing erubis 2.7.0
remote:        Installing journey 1.0.4
remote:        Installing rack 1.4.5
remote:        Installing hike 1.2.3
remote:        Installing mime-types 1.25.1
remote:        Installing tilt 1.4.1
remote:        Installing polyglot 0.3.5
remote:        Installing arel 3.0.3
remote:        Using json 1.8.1
remote:        Installing tzinfo 0.3.42
remote:        Installing addressable 2.3.6
remote:        Installing mini_portile 0.5.3
remote:        Installing uuidtools 2.1.4
remote:        Installing bcrypt 3.1.7 with native extensions
remote:        Installing sass 3.2.13
remote:        Installing thor 0.19.1
remote:        Installing cancancan 1.9.2
remote:        Installing coffee-script-source 1.7.0
remote:        Installing execjs 2.0.2
remote:        Installing cookiejar 0.3.2
remote:        Installing daemons 1.1.9
remote:        Installing orm_adapter 0.5.0
remote:        Installing thread_safe 0.3.3
remote:        Installing eco-source 1.1.0.rc.1
remote:        Installing eventmachine 1.0.3 with native extensions
remote:        Installing http_parser.rb 0.6.0 with native extensions
remote:        Installing websocket-driver 0.3.2 with native extensions
remote:
remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:
remote:        /tmp/build_f93600f1a2d3c92b36aa27f3bcb00821/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160818-231-18l0wkd.rb extconf.rb
remote:        checking for rb_trap_immediate in ruby.h,rubysig.h... no
remote:        checking for rb_thread_blocking_region()... no
remote:        checking for inotify_init() in sys/inotify.h... yes
remote:        checking for writev() in sys/uio.h... yes
remote:        checking for rb_wait_for_single_fd()... yes
remote:        checking for rb_enable_interrupt()... no
remote:        checking for rb_time_new()... yes
remote:        checking for sys/event.h... no
remote:        checking for epoll_create() in sys/epoll.h... yes
remote:        creating Makefile
remote:
remote:        make "DESTDIR=" clean
remote:
remote:        make "DESTDIR="
remote:        compiling cmain.cpp
remote:        compiling pipe.cpp
remote:        compiling binder.cpp
remote:        compiling ssl.cpp
remote:        compiling kb.cpp
remote:        compiling rubymain.cpp
remote:        compiling page.cpp
remote:        compiling em.cpp
remote:        em.cpp: In member function 'void EventMachine_t::_RunEpollOnce()':
remote:        em.cpp:574:37: error: 'rb_thread_select' was not declared in this scope
remote:        EmSelect (0, NULL, NULL, NULL, &tv);
remote:        ^
remote:        em.cpp: In member function 'int SelectData_t::_Select()':
remote:        em.cpp:827:67: error: 'rb_thread_select' was not declared in this scope
remote:        return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
remote:        ^
remote:        em.cpp: In member function 'void EventMachine_t::_RunSelectOnce()':
remote:        em.cpp:946:40: error: 'rb_thread_select' was not declared in this
 scope
remote:        EmSelect (0, NULL, NULL, NULL, &tv);
remote:        ^
remote:        make: **\* [em.o] Error 1
remote:
remote:        make failed, exit code 2
remote:
remote:        Gem files will remain installed in /tmp/build_f93600f1a2d3c92b36a
a27f3bcb00821/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
remote:        Results logged to /tmp/build_f93600f1a2d3c92b36aa27f3bcb00821/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/eventmachine-1.0.3/gem_make.out
remote:        Installing kandan-count 1.1.1
remote:        Installing gemoji 1.5.0
remote:        Installing pg 0.17.1 with native extensions
remote:        Using bundler 1.11.2
remote:        Installing remotipart 1.2.1
remote:        Installing activesupport 3.2.21
remote:        Installing rack-cache 1.2
remote:        Installing rack-test 0.6.2
remote:        Installing rack-ssl 1.3.4
remote:        Installing warden 1.2.3
remote:        Installing sprockets 2.2.3
remote:        Installing treetop 1.4.15
remote:        Installing rdoc 3.12.2
remote:        Installing bootstrap-sass 3.1.1.0
remote:        Installing nokogiri 1.6.1 with native extensions
remote:        Installing bourbon 3.1.8
remote:        Installing coffee-script 2.2.0
remote:        Installing uglifier 2.5.0
remote:        An error occurred while installing eventmachine (1.0.3), and Bundler cannot
remote:        continue.
remote:        Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
remote: !       Push rejected to <name>.
remote:

Warning: Your console font probably doesn't support Unicode. If you experience strange characters in the output, consider switching to a TrueType font such as Consolas!
To https://git.heroku.com/<url>.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/<url>.git
'
`

any ideas?

thanks in advance.

**Comment by marlomajor** [comment]
`Warning: Your console font probably doesn't support Unicode. If you experience strange characters in the output, consider switching to a TrueType font such as Consolas!`

This error is about changing the font in your command prompt.

`error: failed to push some refs to 'https://git.heroku.com/.git`

This error is telling you the upstream repository has changes that would be lost if you pushed to master. Perform a git pull to merge then push again. That should work.
